import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`h-screen flex flex-col`}
      >
        {children}
        {/*<h1 className="asbsolute bottom-0 mt-auto flex mb-3 text-black justify-center">Built with ❤️ by Finn in SC🏖️</h1>*/}
      </body>
    </html>
  );
}
